# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a25c32e835021562adedd248f8fc6855"
name = "quick-ananounce-bar-copy"
handle = "quick-ananounce-bar-copy"
application_url = "https://reach-representative-indicators-connections.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeconfigstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://reach-representative-indicators-connections.trycloudflare.com/auth/callback",
  "https://reach-representative-indicators-connections.trycloudflare.com/auth/shopify/callback",
  "https://reach-representative-indicators-connections.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "collections/create" ]
  uri = "/webhooks/collections/create"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/uninstall"

[pos]
embedded = false
